---
title: "OpzetDewey"
format: typst
editor: visual
bibliography: OverDewey.bib
---

## Dewey

### Waarom Dewey?

### Leven

John Dewey werd op 20 oktober 1859 geboren in de buurt van Burlington, Vermont. Twintig jaar later studeerde hij af aan de Universiteit van Vermont, nadat hij les had gegeven aan openbare scholen in Pennsylvania en Vermont. Dewey was al tijdens zijn studie geïnteresseerd geraakt in filosofische vraagstukken en vervolgde zijn filosofische opleiding aan de John Hopkins University. In 1884 promoveerde hij aan die universiteit tot doctor in de filosofie en kort daarna aanvaardde hij een positie in de filosofie aan de Universiteit van Michigan. Afgezien van een aanstelling van een jaar als professor in de filosofie aan de Universiteit van Minnesota, bleef Dewey vijf jaar als voorzitter aan Michigan verbonden tot hij in 1894 met zijn vrouw, Alice Chipman, naar de Universiteit van Chicago verhuisde en aan zijn ambtstermijn als voorzitter van de afdeling filosofie begon. Het was in Chicago dat Dewey nationale erkenning kreeg voor zijn pionierswerk op het gebied van onderwijs met de ontwikkeling van zijn laboratoriumschool waarin experimentele benaderingen van lesgeven werden onderzocht. Na een ruzie met de Universiteit van Chicago over het bestuur van de school, vertrok Dewey in 1904 en accepteerde hij een hoogleraarschap in de filosofie aan Columbia University.

Gedurende de zesentwintig jaar die volgden diende Deweys academische positie aan Columbia als springplank voor zijn vele en gevarieerde interesses, zoals sociale vraagstukken, politiek, onderwijs en openbare aangelegenheden. Zijn nationale en internationale reputatie bracht hem ertoe samen te werken met groepen als de American Philosophical Association, de American Association of University Professors (oprichter en eerste voorzitter), de Teacher's Union en de American Civil Liberties.

In tegenstelling tot degenen die hun pensioen beschouwen als een tijd om te ontspannen en te genieten van de rustgevende geneugten van het latere leven, wijdde John Dewey zijn resterende jaren aan het oplossen van de moeilijke sociale vraagstukken waar Amerika en de wereld voor stonden.  Hij zette zich in voor organisaties die tot doel hadden het openbaar onderwijs op het gebied van demostiek en internationale politiek te verbeteren. Een van Dewey's beroemdste openbare forums was zijn deelname aan de commissie die in Mexico City bijeenkwam om de aanklachten tegen Leon Trotski tijdens zijn proces in Moskou te onderzoeken. De commissie oordeelde vervolgens dat Trotski onschuldig was aan de aanklachten. Hij was ook één van de collega's die in het openbaar collega-filosoof Betrand Russell verdedigde toen Russell een baan als docent aan het City College van New York werd geweigerd vanwege openbare kritiek op zijn standpunten over huwelijk en religie.

Bij het ontwikkelen van zijn eigen unieke filosofische houding overwon John Dewey het hegeliaanse idealisme om de pragmatische opvattingen van William James te omarmen. Dewey's toewijding aan fee onderzoek en de wetenschappelijke methode bracht hem aan het hoofd van de intellectuele oppositie tegen het geloof dat absolute kennis kan worden bereikt in een wereld van gevarieerde omstandigheden, ontdekkingen, baanbrekend onderzoek en vooruitgang van alle soorten. Voor Dewey is kennis niet absoluut, onveranderlijk en eeuwig, maar eerder relatief ten opzichte van de ontwikkelingsinteractie van de mens met zijn wereld naarmate problemen zich aandienen om opgelost te worden. Deze wetenschappelijke benadering, die het mogelijk maakt om de waarheid van een bewering te verklaren totdat - en alleen totdat - er voldoende negatief bewijs is om de hypothese te ontkrachten, opent de geest voor de noodzaak van een democratische benadering van probleemoplossing. Zonder samenwerking en een rationele tolerantie voor verschillende standpunten binnen een pluralistische gemeenschap heeft de samenleving geen hoop op volwassen ontwikkeling.

Gedurende zijn drieënnegentig jaar schreef John Dewey meer dan twee dozijn boeken en tientallen artikelen in zowel wetenschappelijke als populaire publicaties. Hij is echt Amerika's meest vooraanstaande filosoof, wiens werk intellectuelen over de hele wereld nog vele jaren zal beïnvloeden. 

John Dewey stierf in New York Citsy op 1 juni 1952.


-   Inleiding [@jay2002], [@ryan1995], [@westbrook1991],
-   Absolutism to Experimentism (LW5: 147-160)
-   Kant en Hegel: Kant and Philosophical Method (EW1: 34-47)
-   Darwin: The Influence of Darwinism on Philosophy (MW4: 3-14)
-   James: The Development of American Pragmatism (LW2: 3-21)
-   Praktijk: Chicago and Jane Addams, z'n vrouw en krant, Labschool
-   Samenvatting [@jay2002], [@ryan1995], [@westbrook1991],

### Psycholoog

-   Inleiding[@guideto1970], [@morse2011]
-   New Psychology (EW1: 48-60)
-   Psychological Standpoint (EW1: 122-143),
-   Psychology as Philosophical Method (EW1: 144-167),
-   Boek: Psychology
-   The Reflex Arc Concept (EW5: 96-109)
-   Samenvatting

### Ethicus

-   Inleiding[@pappas2008], [@frega2020]
-   Three Independent Factors in Morals (LW5: 279-288)
-   Boeken: Outline (ES3); StudyEthicsEW4; EthicsMW5; HumanNature (MW14); EthicsLW7
-   Judgement and Knowledge (LW7: 262-283)
-   Place of Habit in Conduct (MW14: 15-62)
-   The Moral Self (LW7: 285-309)
-   Conduct and Experience (LW5: 218-235)
-   Samenvatting (Sauer, 2023)

### Cultuurman

-   Inleiding[@alma2020], [@riedler2024], [@jenkin2017]
-   The Live Creature (LW10: 9-25)
-   By Nature and by Art (LW15: 84-96)
-   Religion versus the Religious (LW9:m3-20)
-   Boeken: CommonFaith (LW9), Art as Experience(LW10)
-   Samenvatting

### Filosoof

-   Inleiding[@bernstein][@menand2001][@shook2023]
-   The Need for a Recovery of Philosophy (MW10: 3-48)
-   Boeken: Leibniz new essays (EW1); German Philosophy and Politics (MW8), Reconstruction (MW12); Quest for Certainty (LW4); Construction and Critcism (LW5); Freedom and Culture (LW13)
-   Escape from Peril (1929/1960, PJD, 355-370)
-   Philosophy's Search of the Immutable (1929/1960, PJD, 371-387)
-   The Pattern of Inquiry (LW12: 105-122)
-   Samenvatting

### Politicus

-   Inleiding[@bishop2007], [@westbrook1991b]
-   Boeken: Public and its Problems (LW2); Individualism (LW5); Liberalism and SA (LW11); Freedom and Culture(LW13)
-   Why I'm not a Communist (1934, APP, nr. 13)
-   The Lost Individual (1930; PJD, 598-607)
-   The Search for the Public (LW2: 238-258)
-   Samenvatting

### Wetenschapper

-   Inleiding[@brown2012], [@guideto1970a]
-   The Problem of Truth (MW6: 12-68)
-   Boeken: Studies in Logical theory (MW2); How We Think (MW6; LW8); Quest for Certainty (LW4); Logic (LW12); Theory of Validation (LW13); Knowing and the Known (LW16)
-   The Place of Judgement in Reflective Activity (LW8: 210-220)
-   Propositions, Warranted Assertibility, and Truth (LW14: 168-188)
-   Samenvatting

### Intellectueel 

-   Inleiding [@jay2002], [@ryan1995], [@westbrook1991], [@ralston2011]
-   Japan en China
-   Turkije, Mexico, Rusland en Zuid-Afrika

-   Oorlog en Vrede
-   Het publiek
-   De Trotsky-zaak
-   Samenvatting (Nichols2024, The death of expertise0

### Onderwijsman 

-   Inleiding (Cremin, 1961; Cremin, 1988, Steffes, 2021)
-   My Pedagogic Creed (\[EW5: 84-95)
-   What is school for (1923, APP, nr 18)
-   The Child and the Curriculum (MW2: 273-291)
-   Boeken: Educational Situation (MW1); Moral principles in Education (MW4); How We Think (MW6; LW8); Interest and effort in Edcuation MW7); Schools of Tomorrow (MW8); Democarcy and Education (MW9); The Source of a Scinece of Education (LW5); Experience and Education (LW13)
-   Democracy and Education in the World of Today (1938; APP, nr 25)
-   Samenvatting [@shook2014] Kauppi

### Democraat

-   Inleiding [@bernsteina], [@shook2014]
-   Democracy is radical (LW11: 296-299)
-   Creative Democracy- The Task Before Us (LW14: 224-230)
-   Boeken: Democracy and Education (MW); xx: Freedom and Culture (LW13)
-   Search for the Great Community (LW2: 325-350)
-   Samenvatting (Hunter, 2024; xx)

### Anderen over Dewey 

 - Sydney Hook;
 - Richard Rorty; 
 - R.J. Bernstein; 
 - Westbrook;
 - Ryan;
 - Jay;
 - Pappas;
 - Shook;
 - West;
 - Rogers

### Tot slot: wat hebben we eraan?
### Literatuur.

::: {#refs}
:::
